"""AceCoin ElectrumX coin definitions.

This adapter targets a Bitcoin-like UTXO chain. Replace the consensus/address
constants with values generated by AceCoin Core before mainnet deployment.
"""

from electrumx.lib import tx as lib_tx
from electrumx.lib.coins import Coin


class AceCoinBase(Coin):
    NAME = "AceCoin"
    SHORTNAME = "ACE"
    NET = None

    VALUE_PER_COIN = 100_000_000
    BASIC_HEADER_SIZE = 80
    CHUNK_SIZE = 2016
    STATIC_BLOCK_HEADERS = True

    # Bitcoin-style defaults. These MUST match AceCoin Core.
    P2PKH_VERBYTE = bytes.fromhex("00")
    P2SH_VERBYTES = (bytes.fromhex("05"),)

    # Placeholder until the real AceCoin genesis block exists.
    GENESIS_HASH = "0" * 64

    # Must match the Core JSON-RPC port.
    RPC_PORT = 9332

    # Generic Bitcoin transaction format.
    DESERIALIZER = lib_tx.DeserializerSegWit

    # Required by ElectrumX for initial-sync estimates.
    TX_COUNT = 1
    TX_COUNT_HEIGHT = 0
    TX_PER_BLOCK = 1


class AceCoinMainnet(AceCoinBase):
    NAME = "AceCoin"
    SHORTNAME = "ACE"
    NET = "mainnet"
    RPC_PORT = 9332


class AceCoinTestnet(AceCoinBase):
    NAME = "AceCoin"
    SHORTNAME = "tACE"
    NET = "testnet"
    RPC_PORT = 19332

    # These address prefixes are placeholders and must match testnet Core.
    P2PKH_VERBYTE = bytes.fromhex("6f")
    P2SH_VERBYTES = (bytes.fromhex("c4"),)


# Force module import and class registration. ElectrumX discovers coin
# implementations by walking subclasses of Coin.
__all__ = ["AceCoinBase", "AceCoinMainnet", "AceCoinTestnet"]
